# Generated by Django 3.1.3 on 2020-11-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default='', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('members_can_control', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
